### ISSUE TITLE
Select county for analysis

### ISSUE THREAD

**Issue by katevcoulter** [MIDS-at-Duke/unifying-data-science-final-project-primaries#10]
for now, try and collect all data for each county of maine. vars needed are:
- voter turnout
- race
-education
-pop density
-age
-education
-ethnicity

**Comment by aberman6** [comment]
We were not able to find complete data for Maine so we pivoted and collected data for Colorado instead.

**Sources**
Colorado turnout data : https://www.sos.state.co.us/pubs/elections/Results/Archives.html
Colorado demo data : https://demography.dola.colorado.gov/population/data/race-estimate/
