### ISSUE TITLE
Pre-post analysis

### ISSUE THREAD

**Issue by aberman6** [MIDS-at-Duke/unifying-data-science-final-project-primaries#13]
Hi Nick,

We're moving into the second portion of our analysis and we wanted to double-check we have the right mindset for our analysis.

Based on our research, we are assuming we can't attach demographic information to individual voter data - it's just not available.

What we _can_ do is compare multiple counties within a single state that made the switch in 2020. By comparing counties with different demographics we can infer that differences in effect are due to differences in county demographics. Is that correct?

Thanks in advance!

**Comment by nickeubank** [comment]
Yup! You could also make guesses about people's demographics using packages the impute race based on names. Something like this: https://pypi.org/project/ethnicolr/ (but I'm not quite sure what "best" package is right now, that was a quick google result).

**Comment by aberman6** [comment]
Awesome, thanks for the quick reply Nick!

**Comment by aberman6** [comment]
Hi @katevcoulter and @shttksm. I ended up collecting turnout and demographic data for all counties in Colorado and doing the bulk of the pre-post analysis. You can find the data set in [02_intermediate_files/turnout_colorado.csv](https://github.com/MIDS-at-Duke/unifying-data-science-final-project-primaries/blob/master/20_intermediate_files/turnout_colorado.csv) and some quick EDA in [03_results/Colorado_EDA.ipynb](https://github.com/MIDS-at-Duke/unifying-data-science-final-project-primaries/blob/master/30_results/Colorado_EDA.ipynb). 

Let's chat and discuss what we can take from this and want to add into our final report tomorrow (Monday) morning. Take a look at the files and let me know if you have any questions in the meantime!

**Comment by katevcoulter** [comment]
yay! thanks @aberman6 ! :) just went through everything and I'll be free to talk tomorrow around 11 am if that works

**Comment by katevcoulter** [comment]
just touched base with anna after looking this over and i think we are set! i'll have the final draft ready for us to go through later today/this evening and we can make final changes tomorrow.
