### ISSUE TITLE
Comments on draft

### ISSUE THREAD

**Issue by nickeubank** [MIDS-at-Duke/unifying-data-science-final-project-primaries#15]
A very nice draft, and very clean diff-in-diff results! A couple thoughts:

- As we've discussed, showing that turnout rose is important, but also not super surprising. Descriptively, the difference between caususes and primaries is so large across so many different states and elections, it's hard to imagine there isn't a causal. So it's great to see the result, but I think you should continue forward by...
- **Showing me changes in voter composition!** I think that's gonna be the most interesting thing. For these same states, how did the composition of the primary electorate change from 2016 to 2020?! Because in some sense, it's not clear we even care about turnout in and of itself (some people might, but others might not) -- what seems to *clearly* be important is whether the types of people voting (and thus the people who are likely to be elected) have changed!

I know you're also working at a single-state voter registry study, but first I'd do the state-level primary-voter composition analysis!

**Comment by katevcoulter** [comment]
Hi @nickeubank ! We are having some issues finding data, but I wanted to follow up with what we do have access to and see your thoughts on it. We cannot find any voter composition data for the states we have in our treatment group. However, we do have for Maine county level turnout for 2016 and 2020 in terms of just numbers (not by demographic, just a lump sum). We also have county level composition not by turnout but just in general. We could infer using the latter what the former could have looked like by composition in some way, correct? Or is there a better option? Let us know!

**Comment by nickeubank** [comment]
hmmmm... proving harder to find than I'd thought it would be. Let me ask a colleague...

The Maine strategy is solid.

**Comment by katevcoulter** [comment]
@nickeubank hi Nick! We are pulling data now and noticed a hiccup. It appears that Maine had an open caucus in 2016 for both Dem and Repub, skewing our numbers a ton. I'm wondering if it was the case that because people could literally show up and decide which caucus to participate in (it appears a huge number of whom decided to participate in the republican caucus) we cannot use these numbers. We **are** getting our numbers from two different websites (politico and our initial data source) and it seems that it is either the case that our initial data source is wrong or politico is counting our numbers so wrong that we get a .2% turnout rate from politico while our initial gives us around 4%. We aren't sure if we should continue with this huge discrepancy or what you would advise us to do otherwise. Any advice?

**Comment by nickeubank** [comment]
I'm just hearing "try exit polls". Roper has 2016 data: https://ropercenter.cornell.edu/exit-polls/state-primary-exit-polls But not sure I can find 2020. May have to stick to an in-state data.

0.2% is clearly insanely low. 

From the voter rolls, can't you just see what voters voted?

**Comment by katevcoulter** [comment]
Roper doesn't have any of our 4 states :(

**Comment by nickeubank** [comment]
damn. 

Do voter rolls have turnout?

**Comment by katevcoulter** [comment]
you mean voter registration numbers? i’m looking at maine.gov <http://maine.gov/> currently and it seems no

**Comment by nickeubank** [comment]
State registrars keep track of who votes in every election and the data is public. Often times if you can find a voter roll – the individual level data on voters – they will include columns on whether people have voted in certain elections.

**Comment by nickeubank** [comment]
So if: 

- You can't find aggregate turnout by race, and 
- You can't find individual level turnout data, 
- then I'd hunt for county-level primary turnout for any of your states and use the trick you were gonna use anyway to do some race imputations by county.

**Comment by nickeubank** [comment]
the far right column here has data sources listed: http://www.electproject.org/2020p

**Comment by aberman6** [comment]
Hi Nick - Serious thank you for looking into this for us. For some inexplicable reason, we can't seem to find caucus turnout for Maine in 2016, only delegate votes by county. I don't know where electproject.org got their data and it's not listed in the notes column at the url you linked us.

After much data searching, I think our best bet is to pivot to Colorado. I was not able to find voter roll, but I was able to find 2016 and 2020 election turnout. If you're curious, the merged dataset is in 20_intermediate_files/turnout_colorado.csv. Once we add demographic data in we can do the same type of county-level analysis we were planning for Maine.
