### ISSUE TITLE
final paper

### ISSUE THREAD

**Issue by katevcoulter** [MIDS-at-Duke/unifying-data-science-final-project-primaries#17]
working on this now!

**Comment by katevcoulter** [comment]
@aberman6 @shttksm let me know when you get a chance to review it - available here: https://docs.google.com/document/d/145qi364ISaf7OCUa1VnXBvzxnm0tYOKFlNl1djXbNAk/edit?usp=sharing

once you guys say it's fine i'll print to PDF and submit!

**Comment by aberman6** [comment]
Just finished cleaning up a couple sections, but it looks great! Shota, let us know what you think.

**Comment by shttksm** [comment]
I also reviewed it. It looks nice.

**Comment by katevcoulter** [comment]
great! pushing it now
