### ISSUE TITLE
final proposal

### ISSUE THREAD

**Issue by katevcoulter** [MIDS-at-Duke/unifying-data-science-final-project-primaries#3]
due april 1 - should include all changes based on our convo with nick on friday march 26

**Comment by aberman6** [comment]
Just uploaded the revised proposal in the docs folder. 
[https://github.com/MIDS-at-Duke/unifying-data-science-final-project-primaries/blob/master/40_docs/Project_Proposal_Revised.docx](url)

Lemme know if you have any questions!

**Comment by katevcoulter** [comment]
final pdf and revision pushed, submitted to gradescope on 3/31

**Comment by nickeubank** [comment]
YAYYY
