### ISSUE TITLE
proposal presentation

### ISSUE THREAD

**Issue by katevcoulter** [MIDS-at-Duke/unifying-data-science-final-project-primaries#4]
due april 6 - should be based on our final proposal

"Your presentations should be 10 minutes, and should generally follow the structure of your project proposals. In particular, you should present:

Motivation (What's the need that motivates your project)
The question you seek to answer
Your ideal experiment (briefly)
How you plan to actually answer your question (>50% of presentation)
In addition, presenters should share their final project proposal with their discussants when they submit it on Wednesday, and should share close-to-done slides 36 hours before you present."

**Comment by katevcoulter** [comment]
meeting on sunday, april 5 to create content and practice

**Comment by aberman6** [comment]
Started a google slide presentation [here](https://docs.google.com/presentation/d/1Tmxs0GES7Z6mQbEaWHW2bHHBmE-g3M-V_Nzv1roSW7I/edit?usp=sharing). Most of it is based on the project proposal. Feel free to edit.

**Comment by katevcoulter** [comment]
just made a few updates, will look more at it this weekend after capstone

**Comment by katevcoulter** [comment]
@shttksm you should def add some sort of commentary on the data section once you add the race variable

**Comment by shttksm** [comment]
@katevcoulter  Sure. I will search for demo data and create merging script by the end of today as well as writing some comments in the data section.

**Comment by aberman6** [comment]
We did it!
