### ISSUE TITLE
add state level race variable

### ISSUE THREAD

**Issue by katevcoulter** [MIDS-at-Duke/unifying-data-science-final-project-primaries#5]

**Comment by shttksm** [comment]
I created a script that merges turnout data and state population by race. 
It would be great if you check.

e23bae60633436aae18bb68d182ec74018cac2a4

## Key points
### state population data by race from 2008 to 2016
* dataset from https://www.kff.org/other/state-indicator/distribution-by-raceethnicity/?dataView=1&currentTimeframe=10&sortModel=%7B%22colId%22:%22Location%22,%22sort%22:%22asc%22%7D based on the Census Bureau's American Community Survey, 2008-2018.

### state population data by race of 2020
* this data set from another website, https://worldpopulationreview.com/states/states-by-race/, that is based on an estimate performed in 2017 (https://www.census.gov/newsroom/press-releases/2017/estimates-idaho.html)
* so, this format is slightly different from those of 2008 - 2016
* especially, this dataset does not have Hispanic categories. It might be assigned to other races, such as white, black, and other races.

**Comment by aberman6** [comment]
Thanks! This looks great.
