### ISSUE TITLE
national difference in difference analysis

### ISSUE THREAD

**Issue by aberman6** [MIDS-at-Duke/unifying-data-science-final-project-primaries#6]

**Comment by aberman6** [comment]
I did a very messy first pass mainly to set up a good pipeline that we can use after we settle the data selection criteria. This analysis:
- Included all states 
- Excluded state years with missing VEP_Counted

Just to be extra clear, I'm not saying this is our final result but it's a good baseline to have. 

<img width="386" alt="Screen Shot 2020-04-14 at 12 54 40 PM" src="https://user-images.githubusercontent.com/16299065/79254719-24064f00-7e53-11ea-89d1-1fa01d1ef5ee.png">
The causal effect is  ~19 % point  increase in votere turnout.

**Comment by katevcoulter** [comment]
hey i think we need to figure out which states we are including before we go any further on this that way we can also work on gathering the county level data / stop pulling data so we don't run into version issues

**Comment by aberman6** [comment]
With the updated exclusion criteria, the D&D looks like this: 
![download](https://user-images.githubusercontent.com/16299065/79491868-15ec3600-7fed-11ea-978b-cfe967f7efca.png)

The causal effect is ~10% point increase in voter turnout.

**Comment by katevcoulter** [comment]
YAY

**Comment by nickeubank** [comment]
Damn!

**Comment by aberman6** [comment]
We realized our dataset was incorrect in reporting of primary vs. caucus. With the updated election types we now have 4 treatment states and 20 control states:

_**Treatment group:** Colorado, Washington, Minnesota, & Maine_

_**Control Group** = Alabama, Arizona, Arkansas, Florida, Iowa, Massachusetts, Michigan, Mississippi, Missouri, Nevada, New Hampshire, North Carolina, North Dakota, Oklahoma, South Carolina, Tennessee, Texas, Utah, Vermont, & Virginia_

Our causal effect is now 15.7 points!
![download-1](https://user-images.githubusercontent.com/16299065/79586542-4096c700-809f-11ea-9560-70e19cb305ad.png)
